### ISSUE TITLE
Persistent firebase-auth

### ISSUE THREAD

**Issue by shihandrana** [StartPolymer/progressive-web-app-template#15]
Hi @JosefJezek ,

I'm new to polymer, writing my first github issue but I do love your template.

I'm trying to use `<firebase-query>` in `app-page-home.html` to fetch data that I pushed in another page (`app-page-new-event.html`, which I make by duplicating the home page). I manage to push the data but I can't fetch it back. 

I opened a [question in stackoverflow](http://stackoverflow.com/questions/43168949/polymerfire-firebase-query-not-working-and-no-error-log) and someone suggest me to use `<firebase-auth>` `sign-in` property. That's where I found that in whatever page, my first load (refreshing the browser) will always result in not-authenticated and when I navigate to the other page, that page will result in authenticated. This happen even though my name is displayed in the top right corner (in `<app-toolbar>`). Therefore, I can't fetch the data on my first load even though I set my firebase rule to public.

Please help.

**Comment by JosefJezek** [comment]
Where run `<firebase-auth>` element? @shihandrana

**Comment by shihandrana** [comment]
Actually, it's a matter of where you put `<firebase-app>`. I solved it somehow (or so I think). https://stackoverflow.com/questions/43154394/polymerfire-cannot-read-property-push-of-undefined/43169473#43169473
