### ISSUE TITLE
Comparison with the Polymer App Toolbox

### ISSUE THREAD

**Issue by dandv** [StartPolymer/progressive-web-app-template#4]
How does this template compare with the [Polymer App Toolbox](https://www.polymer-project.org/1.0/toolbox/)?

**Comment by JosefJezek** [comment]
PWA Template is extended version of `app-drawer-template` with features from this repos https://github.com/StartPolymer/progressive-web-app-template#github-repositories

**Comment by dandv** [comment]
Thanks! Mind contributing back some fixes, e.g. for https://github.com/Polymer/app-drawer-template/issues/20 ?

**Comment by dandv** [comment]
Mind contributing back some fixes, e.g. for https://github.com/Polymer/app-drawer-template/issues/20 ?
