### ISSUE TITLE
help us to deploy same on vps server too

### ISSUE THREAD

**Issue by eraframework** [StartPolymer/progressive-web-app-template#8]
Sir, i have installed node js by comand : sudo npm install -g bower, 
also run sucessfully sudo npm install -g polymer-cli & installed 
polymer-startpolymer

but still i am not able to view polymer project on my linux centos vps server. but if i deploy same to google app engine then its working fine.  kindly help us to deploy same on vps server too

my web server urs is : http://www.cartseller.com/webapp/
app engine : https://webapp-1470592722173.appspot.com/

Regards

**Comment by JosefJezek** [comment]
Look in console... Error 404.

**Comment by eraframework** [comment]
When i inspect element in chrome, it show the code.

**Comment by JosefJezek** [comment]
You have old version of PWA template, merge latest version...

You need all resources on relative URL, check out this line...
https://github.com/StartPolymer/progressive-web-app-template/blob/master/index.html#L178

And set base tag to your path...
https://github.com/StartPolymer/progressive-web-app-template/blob/master/index.html#L14

**Comment by JosefJezek** [comment]
I am working on new version with better support for run app from folder.

**Comment by eraframework** [comment]
Thanks. i will work on your comments tomorrow. if you require server space
for testing then let me know i ll share. Good night
